{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "server.serviceAccountName" . }}
  labels:
{{ include "server.labels" . | indent 4 }}
{{- end -}}
