apiVersion: v1
kind: Service
metadata:
  name: count-server
  labels:
    app: count-server
spec:
  type: ClusterIP
  ports:
    - name: count-server
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: count-server

